#!/bin/bash
# Post-EDA hook: Runs after exploratory data analysis completes
# Saves structured EDA report for downstream agents (feature engineering, preprocessing)

set -e

DATA_PATH="${1:-}"
OUTPUT_DIR="${2:-reports}"

echo "[Post-EDA Hook] Processing EDA results..."

# Create output directories
mkdir -p "$OUTPUT_DIR"
mkdir -p .claude

# 1. Check if EDA report was generated
if [ -f "$OUTPUT_DIR/eda_report.md" ] || [ -f "$OUTPUT_DIR/eda_report.html" ]; then
    echo "  - EDA report found"

    # 2. Extract key metrics for downstream agents
    if [ -f "$OUTPUT_DIR/eda_report.md" ]; then
        echo "  - Extracting metrics for downstream agents..."

        grep -oP 'Rows: \K\d+' "$OUTPUT_DIR/eda_report.md" 2>/dev/null > "$OUTPUT_DIR/.eda_metrics" || true
        grep -oP 'Columns: \K\d+' "$OUTPUT_DIR/eda_report.md" 2>/dev/null >> "$OUTPUT_DIR/.eda_metrics" || true
    fi
fi

# 3. Check for structured EDA report (generated by ml_utils.generate_eda_summary)
if [ -f ".claude/eda_report.json" ]; then
    echo "  - Structured EDA report found at .claude/eda_report.json"
    echo "  - This will be automatically consumed by the feature-engineering-analyst agent"

    # Copy to reports dir as well for persistence
    cp .claude/eda_report.json "$OUTPUT_DIR/eda_report.json" 2>/dev/null || true
else
    echo "  - WARNING: No structured EDA report (.claude/eda_report.json) found"
    echo "    Feature engineering agent will work without prior EDA context"
    echo "    Tip: Use generate_eda_summary() from ml_utils.py to create one"
fi

# 4. Notify about data quality issues
if [ -f "$OUTPUT_DIR/eda_report.md" ]; then
    MISSING_COUNT=$(grep -c "Missing" "$OUTPUT_DIR/eda_report.md" 2>/dev/null || echo "0")
    if [ "$MISSING_COUNT" -gt 5 ]; then
        echo "  - WARNING: $MISSING_COUNT columns with missing values detected"
        echo "    Consider reviewing data quality before proceeding"
    fi
fi

# 5. Log completion with context for agent coordination
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
echo "$TIMESTAMP - EDA completed for $DATA_PATH" >> .claude/workflow.log 2>/dev/null || true

# Signal that EDA is ready for feature engineering
echo "$TIMESTAMP" > .claude/.eda_complete 2>/dev/null || true

echo "[Post-EDA Hook] EDA processing complete! Feature engineering agent can now leverage these results."
